name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0 # Changelog を正しく動作させるために必要

      - uses: actions/setup-go@v5.0.2
        with:
          go-version-file: go.mod
          cache: true

      - uses: goreleaser/goreleaser-action@v6.0.0
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 自動で生成されるシークレット
